version: '3.8'

services:

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    container_name: nodejs-app
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm start"