version: '3.8'

services:

  nodejs-app:
    image: node:16.16.0-alpine3.16
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm start"